window.PUBLIC_RECORDS = [
    {
        "record_id":  "mofa_100_030351",
        "mofa_material_id":  "100-030351",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-030351",
        "legacy_archive_id":  "A\u0027.2.4.1.C(C)1-1",
        "legacy_record_id":  "legacy_a_2_4_1_c_c_1_1_vol1",
        "volume":  "1",
        "title_jp":  "中共要人諸外国訪問　周恩来首相アジア・アフリカ諸国及びアルバニア訪問　第1巻",
        "title_en":  "Premier Zhou Enlai\u0027s Visits to Asian and African Countries and Albania (Vol. 1)",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA;AFRICA",
        "reaction_region_ids":  "",
        "entity_ids":  "PRC;ALB",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Resolved from MOFA API bunruiNo search using corrected classification A\u0027.2.4.1.C(C)1-1 on 2026-06-25. Original local archive_id had an extra parenthesis and combined Vols. 1-2."
    },
    {
        "record_id":  "mofa_100_030352",
        "mofa_material_id":  "100-030352",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-030352",
        "legacy_archive_id":  "A\u0027.2.4.1.C(C)1-1",
        "legacy_record_id":  "legacy_a_2_4_1_c_c_1_1_vol2",
        "volume":  "2",
        "title_jp":  "中共要人諸外国訪問　周恩来首相アジア・アフリカ諸国及びアルバニア訪問　第2巻",
        "title_en":  "Premier Zhou Enlai\u0027s Visits to Asian and African Countries and Albania (Vol. 2)",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA;AFRICA",
        "reaction_region_ids":  "",
        "entity_ids":  "PRC;ALB",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Resolved from MOFA API bunruiNo search using corrected classification A\u0027.2.4.1.C(C)1-1 on 2026-06-25. Original local archive_id had an extra parenthesis and combined Vols. 1-2."
    },
    {
        "record_id":  "mofa_100_050045",
        "mofa_material_id":  "100-050045",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-050045",
        "legacy_archive_id":  "A\u0027.2.4.2.U1-5-4-5",
        "legacy_record_id":  "legacy_a_2_4_2_u1_5_4_5",
        "volume":  "",
        "title_jp":  "ニクソン大統領中華人民共和国訪問 諸外国の態度及び新聞論調 中近東アフリカ諸国",
        "title_en":  "President Nixon\u0027s Visit to the PRC: Reactions and Press Commentary in the Middle East and Africa",
        "release_status":  "Access Review Required",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "MIDEAST;AFRICA",
        "reaction_region_ids":  "",
        "entity_ids":  "USA;PRC",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_023435",
        "mofa_material_id":  "100-023435",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-023435",
        "legacy_archive_id":  "A\u0027.7.1.0.10-3",
        "legacy_record_id":  "legacy_a_7_1_0_10_3_vol2",
        "volume":  "2",
        "title_jp":  "コンゴー動乱 諸外国の態度（第二巻）",
        "title_en":  "The Congo Crisis: Reactions of Foreign Countries (Vol. 2)",
        "release_status":  "Access Review Required",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "AFRICA",
        "reaction_region_ids":  "",
        "entity_ids":  "COD",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Resolved by volume title from MOFA API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_050902",
        "mofa_material_id":  "100-050902",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-050902",
        "legacy_archive_id":  "B\u0027.2.5.0.1-1",
        "legacy_record_id":  "legacy_b_2_5_0_1_1_vol7",
        "volume":  "7",
        "title_jp":  "国際司法裁判所関係一件 裁判官選挙関係（第七巻）",
        "title_en":  "Records Relating to the International Court of Justice: Judicial Elections (Vol. 7)",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "国際司法裁判所：裁判官選挙関係",
        "primary_subject_en":  "International Court of Justice: Judicial Elections",
        "region_ids":  "GLOBAL",
        "reaction_region_ids":  "AFRO_ASIA;ASIA;AFRICA;MIDEAST;EUROPE;AMERICAS",
        "entity_ids":  "",
        "organization_ids":  "ICJ;UN;UNSC",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "SOCIALIST_BLOC",
        "keyword_ids":  "ICJ;DIP;UN;JUDICIAL_ELECTIONS;INTERNATIONAL_ORGANIZATION_ELECTIONS",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Resolved by volume title from MOFA API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_013436",
        "mofa_material_id":  "100-013436",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-013436",
        "legacy_archive_id":  "B\u0027.6.1.0.24",
        "legacy_record_id":  "legacy_b_6_1_0_24_vol1",
        "volume":  "1",
        "title_jp":  "アジア・アフリカ会議関係一件（第一巻）",
        "title_en":  "Records Relating to the Asian-African Conference (Vol. 1)",
        "release_status":  "Access Review Required",
        "years":  "1954-1960",
        "primary_subject_jp":  "アジア・アフリカ会議：会議関係文書および連絡官任命関係",
        "primary_subject_en":  "Asian-African Conference: Conference Records and Liaison Officer Appointments",
        "region_ids":  "ASIA;AFRICA;AFRO_ASIA;SOUTHEAST_ASIA;SOUTH_ASIA;MIDEAST",
        "reaction_region_ids":  "",
        "entity_ids":  "JPN;PAK;LKA;IND;THA;PRC;LAO;LBY;AFG;IRN;DRV;IRQ;NPL;LBR;IDN",
        "organization_ids":  "",
        "related_organization_ids":  "LAS;AA_CONF_JOINT_SECRETARIAT;INDONESIA_MFA;INDONESIA_CONSULATE_GENERAL_TOKYO",
        "event_ids":  "BANDUNG_1955",
        "bloc_ids":  "",
        "keyword_ids":  "AFRO_ASIAN_CONF;BANDUNG_CONFERENCE;CONFERENCE_DIPLOMACY;POST_CONFERENCE_FOLLOW_UP;CONFERENCE_FOLLOW_UP_MECHANISM;DIPLOMATIC_LIAISON;LIAISON_OFFICER_APPOINTMENT;DECOL;THIRD_WORLD;PAN_AFRICAN",
        "analytical_context_ids":  "DECOLONIZATION_AND_UN_DIPLOMACY;COLD_WAR_IN_SOUTHEAST_ASIA",
        "entity_review_required":  "DRV_HISTORICAL_STATE;CEYLON_HISTORICAL_NAME",
        "source_verified_note":  "Updated on 2026-06-25 using user-provided MOFA table of contents and JACAR detail metadata. Record covers general and conference files for the Asian-African Conference and liaison officer appointment files for Japan, Pakistan, Ceylon, India, Thailand, PRC, Laos, Libya, Afghanistan, Iran, Democratic Republic of Vietnam, Iraq, Nepal, and Liberia. Date range updated to 1954-11-01 to 1960-11-30 from user-provided metadata. JACAR parent/detail reference supplied by user: B22010342700; pasted detail includes item-level references including B22010343000-B22010344700. Recurring creators/organizations visible in the JACAR metadata include the League of Arab States Secretariat General, Consulate-General of the Republic of Indonesia in Tokyo, Ministry of Foreign Affairs of the Republic of Indonesia, and the Joint Secretariat of the Asian-African Conference."
    },
    {
        "record_id":  "mofa_100_013440",
        "mofa_material_id":  "100-013440",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-013440",
        "legacy_archive_id":  "B\u0027.6.1.0.24-1-1",
        "legacy_record_id":  "legacy_b_6_1_0_24_1_1_vol2",
        "volume":  "2",
        "title_jp":  "アジア・アフリカ会議一件 日本の態度 参考資料関係（第二巻）",
        "title_en":  "Records Relating to the Asian-African Conference: Japan\u0027s Position and Reference Materials (Vol. 2)",
        "release_status":  "Open",
        "years":  "",
        "primary_subject_jp":  "アジア・アフリカ会議：日本の態度と安全保障関係参考資料",
        "primary_subject_en":  "Asian-African Conference: Japanese Position and Security Reference Materials",
        "region_ids":  "AFRO_ASIA;ASIA;AFRICA",
        "reaction_region_ids":  "",
        "entity_ids":  "JPN;PRC",
        "organization_ids":  "",
        "related_organization_ids":  "SEATO",
        "event_ids":  "BANDUNG_1955",
        "bloc_ids":  "",
        "keyword_ids":  "BANDUNG_CONFERENCE;JAPANESE_POSITION;POLICY_PREPARATION;SECURITY;MILITARY;NUCLEAR_ISSUES;PRC_POSITION_ON_NUCLEAR_ISSUES",
        "analytical_context_ids":  "COLD_WAR_SECURITY_ARCHITECTURE_IN_ASIA;REGIONAL_SECURITY_IN_SOUTHEAST_ASIA;US_ALLIANCE_SYSTEM_IN_ASIA",
        "entity_review_required":  "",
        "source_verified_note":  "Resolved by corrected bunruiNo B\u0027.6.1.0.24-1-1 and volume title from MOFA API on 2026-06-25. Original local archive_id lacked a period after B\u0027."
    },
    {
        "record_id":  "mofa_100_013444",
        "mofa_material_id":  "100-013444",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-013444",
        "legacy_archive_id":  "B\u0027.6.1.0.24-2",
        "legacy_record_id":  "legacy_b_6_1_0_24_2_vol1",
        "volume":  "1",
        "title_jp":  "アジア・アフリカ会議関係一件　諸外国の態度　第1巻",
        "title_en":  "Records Relating to the Asian-African Conference: Positions of Foreign Countries (Vol. 1)",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "アジア・アフリカ会議：諸外国の態度とカシミール・プリンセス号事件",
        "primary_subject_en":  "Asian-African Conference: Foreign Positions and the Kashmir Princess Incident",
        "region_ids":  "ASIA;AFRICA;MIDEAST;AFRO_ASIA;SOUTHEAST_ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "PRC;ROC;IDN;IND;PAK;USA",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "BANDUNG_1955;KASHMIR_PRINCESS_INCIDENT_1955",
        "bloc_ids":  "",
        "keyword_ids":  "BANDUNG_CONFERENCE;FOREIGN_GOVERNMENT_ATTITUDES;GOVERNMENT_REACTIONS;PRC_ROC_COMPETITION;CONFERENCE_DIPLOMACY;SECURITY",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "User verified on current MOFA Diplomatic Archives web search system; material id added 2026-06-25."
    },
    {
        "record_id":  "mofa_100_013459",
        "mofa_material_id":  "100-013459",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-013459",
        "legacy_archive_id":  "B\u0027.6.1.0.25-7",
        "legacy_record_id":  "legacy_b_6_1_0_25_7",
        "volume":  "",
        "title_jp":  "第二回アジア・アフリカ会議関係 各国の参加状況",
        "title_en":  "Second Asian-African Conference: Participation of Individual Countries",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "第二回アジア・アフリカ会議：参加状況・招請・中台承認競争",
        "primary_subject_en":  "Planned Second Asian-African Conference: Participation, Invitations, and PRC-ROC Recognition Competition",
        "region_ids":  "AFRO_ASIA;ASIA;AFRICA;MIDEAST;SOUTHEAST_ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "PRC;ROC;IDN;IND;USA",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "SECOND_AA_CONF_1965_PLANNED",
        "bloc_ids":  "",
        "keyword_ids":  "SECOND_AFRO_ASIAN_CONFERENCE;PARTICIPATION;INVITATION;PARTICIPATION_INTENTION;CONFERENCE_DIPLOMACY;PRC_ROC_COMPETITION;REC;THIRD_WORLD;PAN_AFRICAN",
        "analytical_context_ids":  "DECOLONIZATION_AND_UN_DIPLOMACY;POSTCOLONIAL_STATES_AND_CHINA_REPRESENTATION;THIRD_WORLD_RESPONSES_TO_CHINA_REPRESENTATION",
        "entity_review_required":  "AR_ENTITY_AMBIGUOUS;I_ENTITY_AMBIGUOUS;IV_ENTITY_AMBIGUOUS;TZ_ENTITY_AMBIGUOUS;ARAB_UNION_ENTITY_AMBIGUOUS;CONGO_ENTITY_AMBIGUOUS;VIETNAM_ENTITY_AMBIGUOUS",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_051612",
        "mofa_material_id":  "100-051612",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-051612",
        "legacy_archive_id":  "C\u0027.1.1.0.1",
        "legacy_record_id":  "legacy_c_1_1_0_1",
        "volume":  "",
        "title_jp":  "各国兵役関係雑件",
        "title_en":  "Miscellaneous Records on Military Service in Various Countries",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA;MIDEAST;AFRICA",
        "reaction_region_ids":  "",
        "entity_ids":  "PRC;ROC;IRN;MAR;EGY;ZAF;TUR",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_112015",
        "mofa_material_id":  "100-112015",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-112015",
        "legacy_archive_id":  "C\u0027.4.2.0.1",
        "legacy_record_id":  "legacy_c_4_2_0_1_vol2",
        "volume":  "2",
        "title_jp":  "各国兵器関係（第二巻）",
        "title_en":  "Weapons and Armaments in Various Countries (Vol. 2)",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA_PACIFIC;MIDEAST;AFRICA",
        "reaction_region_ids":  "",
        "entity_ids":  "AUS;SGP;PRC;THA;NZL;IND;IDN;SYR;TUR;ISR;EGY;KEN",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Resolved by volume title from MOFA API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_000928",
        "mofa_material_id":  "100-000928",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-000928",
        "legacy_archive_id":  "M\u0027.3.1.7.8-2-4",
        "legacy_record_id":  "legacy_m_3_1_7_8_2_4_vol1",
        "volume":  "1",
        "title_jp":  "在外公館長会議関係 アジア、太平洋地域公館公館長会議 第四回（第一巻）",
        "title_en":  "Meetings of Chiefs of Overseas Missions: Fourth Meeting of Chiefs of Missions in the Asia-Pacific Region (Vol. 1)",
        "release_status":  "Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA_PACIFIC",
        "reaction_region_ids":  "",
        "entity_ids":  "JPN",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Resolved by volume title from MOFA API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_053589",
        "mofa_material_id":  "100-053589",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-053589",
        "legacy_archive_id":  "M\u0027.3.1.7.8-6-5",
        "legacy_record_id":  "legacy_m_3_1_7_8_6_5_vol2",
        "volume":  "2",
        "title_jp":  "在外公館長会議関係 中近東地域公館長会議 第五回会議関係（第二巻）",
        "title_en":  "Meetings of Chiefs of Overseas Missions: Fifth Meeting of Chiefs of Missions in the Middle East Region (Vol. 2)",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "MIDEAST",
        "reaction_region_ids":  "",
        "entity_ids":  "JPN",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Resolved by volume title from MOFA API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_006322",
        "mofa_material_id":  "100-006322",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-006322",
        "legacy_archive_id":  "2011-0710",
        "legacy_record_id":  "legacy_2011_0710",
        "volume":  "",
        "title_jp":  "日中国交正常化（諸外国の反応）",
        "title_en":  "Normalization of Japan-PRC Relations: Reactions of Foreign Countries",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "JPN;PRC;ROC;TWN",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_006324",
        "mofa_material_id":  "100-006324",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-006324",
        "legacy_archive_id":  "2011-0712",
        "legacy_record_id":  "legacy_2011_0712",
        "volume":  "",
        "title_jp":  "日中国交正常化（諸外国の反応）",
        "title_en":  "Normalization of Japan-PRC Relations: Reactions of Foreign Countries",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "JPN;PRC;ROC;TWN",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_006326",
        "mofa_material_id":  "100-006326",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-006326",
        "legacy_archive_id":  "2011-0714",
        "legacy_record_id":  "legacy_2011_0714",
        "volume":  "",
        "title_jp":  "日中国交正常化（田中総理中国訪問（諸外国の反応））",
        "title_en":  "Normalization of Japan-PRC Relations: Reactions of Foreign Countries to Prime Minister Tanaka\u0027s Visit to China",
        "release_status":  "Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "JPN;PRC;TWN",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_006897",
        "mofa_material_id":  "100-006897",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-006897",
        "legacy_archive_id":  "2013-3308",
        "legacy_record_id":  "legacy_2013_3308",
        "volume":  "",
        "title_jp":  "日中関係",
        "title_en":  "Japan-China Relations",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "JPN;PRC;CHN_AMBIG",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_110350",
        "mofa_material_id":  "100-110350",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-110350",
        "legacy_archive_id":  "2016-0275",
        "legacy_record_id":  "legacy_2016_0275",
        "volume":  "",
        "title_jp":  "日中関係(総理/大臣等発言要領)",
        "title_en":  "Japan-China Relations: Statements by the Prime Minister, Ministers, and Other Officials",
        "release_status":  "Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "JPN;PRC;CHN_AMBIG",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_101788",
        "mofa_material_id":  "100-101788",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-101788",
        "legacy_archive_id":  "2014-3076",
        "legacy_record_id":  "legacy_2014_3076",
        "volume":  "",
        "title_jp":  "華国鋒中国国務院総理訪日/報道振り返り",
        "title_en":  "Visit to Japan by PRC Premier Hua Guofeng: Press Review",
        "release_status":  "Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "JPN;PRC",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_111122",
        "mofa_material_id":  "100-111122",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-111122",
        "legacy_archive_id":  "2016-1326",
        "legacy_record_id":  "legacy_2016_1326",
        "volume":  "",
        "title_jp":  "米国政治（含、対日関係）",
        "title_en":  "United States Politics, Including Relations with Japan",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "NORTH_AMERICA",
        "reaction_region_ids":  "EAST_ASIA;SOUTH_ASIA;MIDEAST;AFRICA;LATIN_AMERICA;CENTRAL_AMERICA;GLOBAL",
        "entity_ids":  "USA;JPN",
        "organization_ids":  "UN;UNGA",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_077384",
        "mofa_material_id":  "100-077384",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-077384",
        "legacy_archive_id":  "2013-0327",
        "legacy_record_id":  "legacy_2013_0327",
        "volume":  "",
        "title_jp":  "ニュー・ジーランド外交",
        "title_en":  "New Zealand Diplomacy",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA_PACIFIC",
        "reaction_region_ids":  "",
        "entity_ids":  "NZL",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "ASIAN_FREE_WORLD;ASIAN_COMMUNIST_BLOC",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_110682",
        "mofa_material_id":  "100-110682",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-110682",
        "legacy_archive_id":  "2016-0860",
        "legacy_record_id":  "legacy_2016_0860",
        "volume":  "",
        "title_jp":  "ニュー・ジーランド外交",
        "title_en":  "New Zealand Diplomacy",
        "release_status":  "Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA_PACIFIC",
        "reaction_region_ids":  "",
        "entity_ids":  "NZL",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_006829",
        "mofa_material_id":  "100-006829",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-006829",
        "legacy_archive_id":  "2013-2429",
        "legacy_record_id":  "legacy_2013_2429",
        "volume":  "",
        "title_jp":  "中共・アフリカ諸国関係",
        "title_en":  "PRC-Africa Relations",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "AFRICA",
        "reaction_region_ids":  "",
        "entity_ids":  "PRC",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_070115",
        "mofa_material_id":  "100-070115",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-070115",
        "legacy_archive_id":  "2013-2430",
        "legacy_record_id":  "legacy_2013_2430",
        "volume":  "",
        "title_jp":  "中共・アフリカ諸国関係",
        "title_en":  "PRC-Africa Relations",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "AFRICA",
        "reaction_region_ids":  "",
        "entity_ids":  "PRC",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_070114",
        "mofa_material_id":  "100-070114",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-070114",
        "legacy_archive_id":  "2013-2431",
        "legacy_record_id":  "legacy_2013_2431",
        "volume":  "",
        "title_jp":  "中共・アフリカ諸国関係",
        "title_en":  "PRC-Africa Relations",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "AFRICA",
        "reaction_region_ids":  "",
        "entity_ids":  "PRC",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_070860",
        "mofa_material_id":  "100-070860",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-070860",
        "legacy_archive_id":  "2013-2432",
        "legacy_record_id":  "legacy_2013_2432",
        "volume":  "",
        "title_jp":  "中共・アフリカ諸国関係",
        "title_en":  "PRC-Africa Relations",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "AFRICA",
        "reaction_region_ids":  "",
        "entity_ids":  "PRC",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_070113",
        "mofa_material_id":  "100-070113",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-070113",
        "legacy_archive_id":  "2013-2433",
        "legacy_record_id":  "legacy_2013_2433",
        "volume":  "",
        "title_jp":  "中共・中近東、アフリカ諸国関係",
        "title_en":  "PRC Relations with the Middle East and African Countries",
        "release_status":  "Access Review Required",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "MIDEAST;AFRICA",
        "reaction_region_ids":  "",
        "entity_ids":  "PRC",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_070337",
        "mofa_material_id":  "100-070337",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-070337",
        "legacy_archive_id":  "2013-2434",
        "legacy_record_id":  "legacy_2013_2434",
        "volume":  "",
        "title_jp":  "中共・中近東、アフリカ諸国関係",
        "title_en":  "PRC Relations with the Middle East and African Countries",
        "release_status":  "Access Review Required",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "MIDEAST;AFRICA",
        "reaction_region_ids":  "",
        "entity_ids":  "PRC",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_070338",
        "mofa_material_id":  "100-070338",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-070338",
        "legacy_archive_id":  "2013-2435",
        "legacy_record_id":  "legacy_2013_2435",
        "volume":  "",
        "title_jp":  "中共・中近東、アフリカ諸国関係",
        "title_en":  "PRC Relations with the Middle East and African Countries",
        "release_status":  "Access Review Required",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "MIDEAST;AFRICA",
        "reaction_region_ids":  "",
        "entity_ids":  "PRC",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "NAM_SUMMIT_3_1970",
        "bloc_ids":  "NON_ALIGNED_MOVEMENT",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_070859",
        "mofa_material_id":  "100-070859",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-070859",
        "legacy_archive_id":  "2013-2436",
        "legacy_record_id":  "legacy_2013_2436",
        "volume":  "",
        "title_jp":  "中共・中近東、アフリカ諸国関係",
        "title_en":  "PRC Relations with the Middle East and African Countries",
        "release_status":  "Access Review Required",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "MIDEAST;AFRICA",
        "reaction_region_ids":  "",
        "entity_ids":  "PRC",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_070116",
        "mofa_material_id":  "100-070116",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-070116",
        "legacy_archive_id":  "2013-2437",
        "legacy_record_id":  "legacy_2013_2437",
        "volume":  "",
        "title_jp":  "中共・中近東、アフリカ諸国関係",
        "title_en":  "PRC Relations with the Middle East and African Countries",
        "release_status":  "Access Review Required",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "MIDEAST;AFRICA",
        "reaction_region_ids":  "",
        "entity_ids":  "PRC",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_112859",
        "mofa_material_id":  "100-112859",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-112859",
        "legacy_archive_id":  "2017-0035",
        "legacy_record_id":  "legacy_2017_0035",
        "volume":  "",
        "title_jp":  "中国・ソ連関係",
        "title_en":  "Sino-Soviet Relations",
        "release_status":  "Access Review Required",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "PRC;USSR",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_070132",
        "mofa_material_id":  "100-070132",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-070132",
        "legacy_archive_id":  "2012-1600",
        "legacy_record_id":  "legacy_2012_1600",
        "volume":  "",
        "title_jp":  "ビルマ外交",
        "title_en":  "Burmese Diplomacy",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "MMR",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_043360",
        "mofa_material_id":  "100-043360",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-043360",
        "legacy_archive_id":  "2010-5146",
        "legacy_record_id":  "legacy_2010_5146",
        "volume":  "",
        "title_jp":  "アンゴラ独立/各国承認状況",
        "title_en":  "Angolan Independence: Recognition by Various Countries",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "AFRICA",
        "reaction_region_ids":  "",
        "entity_ids":  "AGO",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_112095",
        "mofa_material_id":  "100-112095",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-112095",
        "legacy_archive_id":  "2016-2224",
        "legacy_record_id":  "legacy_2016_2224",
        "volume":  "",
        "title_jp":  "中東情勢",
        "title_en":  "Middle East Situation",
        "release_status":  "Access Review Required",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "MIDEAST",
        "reaction_region_ids":  "",
        "entity_ids":  "",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "SOCIALIST_BLOC",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_075248",
        "mofa_material_id":  "100-075248",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-075248",
        "legacy_archive_id":  "2012-3120",
        "legacy_record_id":  "legacy_2012_3120",
        "volume":  "",
        "title_jp":  "中東情勢",
        "title_en":  "Middle East Situation",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "MIDEAST",
        "reaction_region_ids":  "",
        "entity_ids":  "",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_075249",
        "mofa_material_id":  "100-075249",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-075249",
        "legacy_archive_id":  "2012-3121",
        "legacy_record_id":  "legacy_2012_3121",
        "volume":  "",
        "title_jp":  "中東情勢",
        "title_en":  "Middle East Situation",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "MIDEAST",
        "reaction_region_ids":  "",
        "entity_ids":  "",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_075256",
        "mofa_material_id":  "100-075256",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-075256",
        "legacy_archive_id":  "2012-3122",
        "legacy_record_id":  "legacy_2012_3122",
        "volume":  "",
        "title_jp":  "中東情勢",
        "title_en":  "Middle East Situation",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "MIDEAST",
        "reaction_region_ids":  "",
        "entity_ids":  "",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_075268",
        "mofa_material_id":  "100-075268",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-075268",
        "legacy_archive_id":  "2012-3153",
        "legacy_record_id":  "legacy_2012_3153",
        "volume":  "",
        "title_jp":  "中東情勢",
        "title_en":  "Middle East Situation",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "MIDEAST",
        "reaction_region_ids":  "",
        "entity_ids":  "",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_073346",
        "mofa_material_id":  "100-073346",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-073346",
        "legacy_archive_id":  "2011-0082",
        "legacy_record_id":  "legacy_2011_0082",
        "volume":  "",
        "title_jp":  "カンボディア問題",
        "title_en":  "Cambodian Question",
        "release_status":  "Access Review Required",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "KHM",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_006256",
        "mofa_material_id":  "100-006256",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-006256",
        "legacy_archive_id":  "2011-0092",
        "legacy_record_id":  "legacy_2011_0092",
        "volume":  "",
        "title_jp":  "カンボディア問題（含、カンボディア民族連合王国政府）",
        "title_en":  "Cambodian Question, Including the Royal Government of National Union of Cambodia",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "KHM",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_006840",
        "mofa_material_id":  "100-006840",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-006840",
        "legacy_archive_id":  "2013-2495",
        "legacy_record_id":  "legacy_2013_2495",
        "volume":  "",
        "title_jp":  "中共・インド国境紛争",
        "title_en":  "Sino-Indian Border Conflict",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "PRC;IND",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_070112",
        "mofa_material_id":  "100-070112",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-070112",
        "legacy_archive_id":  "2013-3457",
        "legacy_record_id":  "legacy_2013_3457",
        "volume":  "",
        "title_jp":  "中共・インド国境紛争",
        "title_en":  "Sino-Indian Border Conflict",
        "release_status":  "Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "PRC;IND",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_102145",
        "mofa_material_id":  "100-102145",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-102145",
        "legacy_archive_id":  "2014-3238",
        "legacy_record_id":  "legacy_2014_3238",
        "volume":  "",
        "title_jp":  "アフガニスタン問題",
        "title_en":  "Afghanistan Question",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "AFG",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_111045",
        "mofa_material_id":  "100-111045",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-111045",
        "legacy_archive_id":  "2016-1363",
        "legacy_record_id":  "legacy_2016_1363",
        "volume":  "",
        "title_jp":  "中東問題/紅海における爆雷爆発事件",
        "title_en":  "Middle East Question: Mine Explosion Incident in the Red Sea",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "MIDEAST",
        "reaction_region_ids":  "",
        "entity_ids":  "",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_113375",
        "mofa_material_id":  "100-113375",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-113375",
        "legacy_archive_id":  "2017-0685",
        "legacy_record_id":  "legacy_2017_0685",
        "volume":  "",
        "title_jp":  "中東問題",
        "title_en":  "Middle East Question",
        "release_status":  "Access Review Required",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "MIDEAST",
        "reaction_region_ids":  "",
        "entity_ids":  "",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_114105",
        "mofa_material_id":  "100-114105",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-114105",
        "legacy_archive_id":  "2018-0150",
        "legacy_record_id":  "legacy_2018_0150",
        "volume":  "",
        "title_jp":  "イラン・イラク問題",
        "title_en":  "Iran-Iraq Question",
        "release_status":  "Access Review Required",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "MIDEAST",
        "reaction_region_ids":  "",
        "entity_ids":  "IRN;IRQ",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_116354",
        "mofa_material_id":  "100-116354",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-116354",
        "legacy_archive_id":  "2019-0762",
        "legacy_record_id":  "legacy_2019_0762",
        "volume":  "",
        "title_jp":  "イラン・イラク問題",
        "title_en":  "Iran-Iraq Question",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "MIDEAST",
        "reaction_region_ids":  "",
        "entity_ids":  "IRN;IRQ",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_116345",
        "mofa_material_id":  "100-116345",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-116345",
        "legacy_archive_id":  "2019-0768",
        "legacy_record_id":  "legacy_2019_0768",
        "volume":  "",
        "title_jp":  "イラン・イラク問題",
        "title_en":  "Iran-Iraq Question",
        "release_status":  "Access Review Required",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "MIDEAST",
        "reaction_region_ids":  "",
        "entity_ids":  "IRN;IRQ",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_076469",
        "mofa_material_id":  "100-076469",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-076469",
        "legacy_archive_id":  "2014-0899",
        "legacy_record_id":  "legacy_2014_0899",
        "volume":  "",
        "title_jp":  "トルコ外交",
        "title_en":  "Turkish Diplomacy",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "MIDEAST",
        "reaction_region_ids":  "",
        "entity_ids":  "TUR",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_109865",
        "mofa_material_id":  "100-109865",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-109865",
        "legacy_archive_id":  "2016-0063",
        "legacy_record_id":  "legacy_2016_0063",
        "volume":  "",
        "title_jp":  "西独外交",
        "title_en":  "West German Diplomacy",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "EUROPE;WESTERN_EUROPE",
        "reaction_region_ids":  "EASTERN_EUROPE;ASIA;EAST_ASIA;SOUTHEAST_ASIA;SOUTH_ASIA;LATIN_AMERICA;MIDEAST;AFRICA",
        "entity_ids":  "DEU_W",
        "organization_ids":  "EC",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_005244",
        "mofa_material_id":  "100-005244",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-005244",
        "legacy_archive_id":  "2009-0721",
        "legacy_record_id":  "legacy_2009_0721",
        "volume":  "",
        "title_jp":  "中国・諸外国間貿易協定",
        "title_en":  "Trade Agreements between the PRC and Foreign Countries",
        "release_status":  "Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "PRC",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_071248",
        "mofa_material_id":  "100-071248",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-071248",
        "legacy_archive_id":  "2013-3130",
        "legacy_record_id":  "legacy_2013_3130",
        "volume":  "",
        "title_jp":  "中共貿易/統計，資料（含、対日関係）",
        "title_en":  "PRC Trade: Statistics and Reference Materials (Including Relations with Japan)",
        "release_status":  "Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "PRC;JPN",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "SOCIALIST_BLOC",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_071249",
        "mofa_material_id":  "100-071249",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-071249",
        "legacy_archive_id":  "2013-3131",
        "legacy_record_id":  "legacy_2013_3131",
        "volume":  "",
        "title_jp":  "中共対外経済援助",
        "title_en":  "PRC Foreign Economic Assistance",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA;AFRICA;MIDEAST",
        "reaction_region_ids":  "",
        "entity_ids":  "PRC",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "SOCIALIST_BLOC",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_005461",
        "mofa_material_id":  "100-005461",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-005461",
        "legacy_archive_id":  "2010-1116",
        "legacy_record_id":  "legacy_2010_1116",
        "volume":  "",
        "title_jp":  "国連",
        "title_en":  "United Nations",
        "release_status":  "Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "GLOBAL;ASIA;AFRICA",
        "reaction_region_ids":  "EAST_ASIA;ASIA;AFRICA",
        "entity_ids":  "",
        "organization_ids":  "UN",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_006060",
        "mofa_material_id":  "100-006060",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-006060",
        "legacy_archive_id":  "2010-5183",
        "legacy_record_id":  "legacy_2010_5183",
        "volume":  "",
        "title_jp":  "国連",
        "title_en":  "United Nations",
        "release_status":  "Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA;EAST_ASIA;SOUTHEAST_ASIA",
        "reaction_region_ids":  "ASIA_PACIFIC;SOUTH_ASIA;OCEANIA;GLOBAL",
        "entity_ids":  "",
        "organization_ids":  "UN;WMO;ECAFE",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_103098",
        "mofa_material_id":  "100-103098",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-103098",
        "legacy_archive_id":  "2014-4131",
        "legacy_record_id":  "legacy_2014_4131",
        "volume":  "",
        "title_jp":  "国連代表権問題/中共",
        "title_en":  "Question of China\u0027s Representation in the United Nations",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "PRC;ROC;CHN_AMBIG;TWN",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_103100",
        "mofa_material_id":  "100-103100",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-103100",
        "legacy_archive_id":  "2014-4133",
        "legacy_record_id":  "legacy_2014_4133",
        "volume":  "",
        "title_jp":  "国連代表権問題/中共",
        "title_en":  "Question of China\u0027s Representation in the United Nations",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "GLOBAL;EAST_ASIA",
        "reaction_region_ids":  "NORTH_AMERICA;WESTERN_EUROPE;EUROPE;ASIA;EASTERN_EUROPE;OCEANIA;LATIN_AMERICA;AFRICA;MIDEAST",
        "entity_ids":  "PRC;ROC;USA;AUS;NZL",
        "organization_ids":  "UN;UNGA",
        "related_organization_ids":  "",
        "event_ids":  "UNGA_26_1971",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "DECOLONIZATION_AND_UN_DIPLOMACY;POSTCOLONIAL_STATES_AND_CHINA_REPRESENTATION;THIRD_WORLD_RESPONSES_TO_CHINA_REPRESENTATION",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_101500",
        "mofa_material_id":  "100-101500",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-101500",
        "legacy_archive_id":  "2014-2744",
        "legacy_record_id":  "legacy_2014_2744",
        "volume":  "",
        "title_jp":  "国連中国代表権問題/中共（各国の態度）",
        "title_en":  "Question of China\u0027s Representation in the United Nations: Attitudes of Various Countries",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "国連中国代表権問題：ラテンアメリカ・アフリカ・オセアニア諸国の態度",
        "primary_subject_en":  "Question of China\u0027s Representation in the United Nations: Attitudes of Latin American, African, and Oceanian Countries",
        "region_ids":  "GLOBAL;EAST_ASIA",
        "reaction_region_ids":  "LATIN_AMERICA;AFRICA;OCEANIA",
        "entity_ids":  "PRC;ROC;COL;VEN;ARG;ECU;MEX;BRA;PAN;PRY;URY;DOM;BOL;CHL;PER;CIV;GHA;ZAF;MDG;SEN;KEN;AUS;NZL",
        "organization_ids":  "UN;UNGA",
        "related_organization_ids":  "",
        "event_ids":  "UNGA_26_1971",
        "bloc_ids":  "",
        "keyword_ids":  "UN_CHINA_REPRESENTATION_ISSUE;VOTING_BEHAVIOR;VOTE_COUNTING;DIPLOMATIC_LOBBYING;SUPPORT_REQUEST;FOREIGN_GOVERNMENT_ATTITUDES;JAPANESE_DIPLOMATIC_REPORTING;PRC_ROC_COMPETITION",
        "analytical_context_ids":  "FRENCH_COLONIAL_LEGACY_IN_AFRICA;POSTCOLONIAL_STATES_AND_CHINA_REPRESENTATION;DECOLONIZATION_AND_UN_DIPLOMACY",
        "entity_review_required":  "CONGO_ENTITY_AMBIGUOUS",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_108902",
        "mofa_material_id":  "100-108902",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-108902",
        "legacy_archive_id":  "2015-2086",
        "legacy_record_id":  "legacy_2015_2086",
        "volume":  "",
        "title_jp":  "国連中国代表権問題/中共（各国の態度）",
        "title_en":  "Question of China\u0027s Representation in the United Nations: Attitudes of Various Countries",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "国連中国代表権問題：ニクソン訪中発表前後の中華民国および諸外国の態度",
        "primary_subject_en":  "UN China Representation: ROC and Foreign Reactions around the Announcement of Nixon\u0027s Visit to the PRC",
        "region_ids":  "GLOBAL;EAST_ASIA",
        "reaction_region_ids":  "GLOBAL",
        "entity_ids":  "PRC;ROC;USA",
        "organization_ids":  "UN;UNGA",
        "related_organization_ids":  "",
        "event_ids":  "NIXON_CHINA_VISIT_ANNOUNCEMENT_1971;UNGA_26_1971",
        "bloc_ids":  "",
        "keyword_ids":  "UN_CHINA_REPRESENTATION_ISSUE;US_PRC_RAPPROCHEMENT;NIXON_VISIT_TO_PRC;FOREIGN_GOVERNMENT_ATTITUDES;JAPANESE_DIPLOMATIC_REPORTING;PRC_ROC_COMPETITION;VOTING_BEHAVIOR;VOTE_COUNTING",
        "analytical_context_ids":  "DECOLONIZATION_AND_UN_DIPLOMACY;POSTCOLONIAL_STATES_AND_CHINA_REPRESENTATION",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_108900",
        "mofa_material_id":  "100-108900",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-108900",
        "legacy_archive_id":  "2015-2085",
        "legacy_record_id":  "legacy_2015_2085",
        "volume":  "",
        "title_jp":  "国連代表権問題/中共（アジア、中近東、アフリカ諸国の態度）",
        "title_en":  "Question of China\u0027s Representation in the United Nations: Attitudes of Asian, Middle Eastern, and African Countries",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "国連中国代表権問題：第26回国連総会に向けたアジア・中近東・アフリカ諸国の態度",
        "primary_subject_en":  "UN China Representation: Attitudes of Asian, Middle Eastern, and African Countries before the 26th UN General Assembly",
        "region_ids":  "GLOBAL;EAST_ASIA",
        "reaction_region_ids":  "ASIA;MIDEAST;AFRICA",
        "entity_ids":  "PRC;ROC",
        "organization_ids":  "UN;UNGA",
        "related_organization_ids":  "",
        "event_ids":  "UNGA_25_1970;UNGA_26_1971",
        "bloc_ids":  "",
        "keyword_ids":  "UN_CHINA_REPRESENTATION_ISSUE;VOTING_BEHAVIOR;VOTE_COUNTING;FOREIGN_GOVERNMENT_ATTITUDES;JAPANESE_DIPLOMATIC_REPORTING;PRC_ROC_COMPETITION;DIPLOMATIC_LOBBYING",
        "analytical_context_ids":  "DECOLONIZATION_AND_UN_DIPLOMACY;POSTCOLONIAL_STATES_AND_CHINA_REPRESENTATION;THIRD_WORLD_RESPONSES_TO_CHINA_REPRESENTATION",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_115122",
        "mofa_material_id":  "100-115122",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-115122",
        "legacy_archive_id":  "2018-0965",
        "legacy_record_id":  "legacy_2018_0965",
        "volume":  "",
        "title_jp":  "国連に関する日・諸外国協議",
        "title_en":  "Japan\u0027s Consultations with Foreign Countries on the United Nations",
        "release_status":  "Access Review Required",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "GLOBAL",
        "reaction_region_ids":  "",
        "entity_ids":  "JPN",
        "organization_ids":  "UN",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_042833",
        "mofa_material_id":  "100-042833",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-042833",
        "legacy_archive_id":  "2010-1215",
        "legacy_record_id":  "legacy_2010_1215",
        "volume":  "",
        "title_jp":  "国連第30回総会",
        "title_en":  "Thirtieth Session of the United Nations General Assembly",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "国連第30回総会：会談・招待行事・日程調整",
        "primary_subject_en":  "30th Session of the United Nations General Assembly: Meetings, Invitations, and Schedule Coordination",
        "region_ids":  "GLOBAL",
        "reaction_region_ids":  "",
        "entity_ids":  "",
        "organization_ids":  "UN;UNGA",
        "related_organization_ids":  "",
        "event_ids":  "UNGA_30_1975",
        "bloc_ids":  "",
        "keyword_ids":  "UNGA;UN;DIP;JAPANESE_DIPLOMATIC_REPORTING",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_101842",
        "mofa_material_id":  "100-101842",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-101842",
        "legacy_archive_id":  "2014-3472",
        "legacy_record_id":  "legacy_2014_3472",
        "volume":  "",
        "title_jp":  "国連 カンボディア問題国際会議",
        "title_en":  "United Nations International Conference on the Cambodian Question",
        "release_status":  "Open",
        "years":  "",
        "primary_subject_jp":  "カンボジア問題国際会議",
        "primary_subject_en":  "International Conference on Cambodia",
        "region_ids":  "ASIA;SOUTHEAST_ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "KHM;VNM;PRC",
        "organization_ids":  "UN;ASEAN",
        "related_organization_ids":  "",
        "event_ids":  "CAMBODIA_INTL_CONFERENCE_1981",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "COLD_WAR_IN_SOUTHEAST_ASIA;SOUTHEAST_ASIAN_COMMUNIST_POLITICS;SINO_SOVIET_RIVALRY_IN_SOUTHEAST_ASIA;PRC_VIETNAM_RIVALRY;REGIONAL_IDEOLOGICAL_CONFLICT;COMMUNIST_PARTY_POLITICS",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_072714",
        "mofa_material_id":  "100-072714",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-072714",
        "legacy_archive_id":  "2011-0193",
        "legacy_record_id":  "legacy_2011_0193",
        "volume":  "",
        "title_jp":  "UNCTAD第三回総会",
        "title_en":  "Third Session of UNCTAD",
        "release_status":  "Access Review Required",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "GLOBAL",
        "reaction_region_ids":  "",
        "entity_ids":  "",
        "organization_ids":  "UN;UNCTAD",
        "related_organization_ids":  "",
        "event_ids":  "UNCTAD_III_1972",
        "bloc_ids":  "GROUP_OF_77;GROUP_B;ASIAN_GROUP;AFRICAN_GROUP",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_103124",
        "mofa_material_id":  "100-103124",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-103124",
        "legacy_archive_id":  "2014-4153",
        "legacy_record_id":  "legacy_2014_4153",
        "volume":  "",
        "title_jp":  "諸外国国防・軍事",
        "title_en":  "National Defense and Military Affairs in Foreign Countries",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "GLOBAL",
        "reaction_region_ids":  "",
        "entity_ids":  "",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_005850",
        "mofa_material_id":  "100-005850",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-005850",
        "legacy_archive_id":  "2010-4088",
        "legacy_record_id":  "legacy_2010_4088",
        "volume":  "",
        "title_jp":  "日韓経済協力案件（国別経済協力）",
        "title_en":  "Japan-ROK Economic Cooperation Projects (Country-Specific Economic Cooperation)",
        "release_status":  "Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "JPN;KOR",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_006643",
        "mofa_material_id":  "100-006643",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-006643",
        "legacy_archive_id":  "2012-3234",
        "legacy_record_id":  "legacy_2012_3234",
        "volume":  "",
        "title_jp":  "フランス・中共外交関係樹立",
        "title_en":  "Establishment of Diplomatic Relations between France and the PRC",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "FRA;PRC;ROC;TWN",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_113427",
        "mofa_material_id":  "100-113427",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-113427",
        "legacy_archive_id":  "2017-0657",
        "legacy_record_id":  "legacy_2017_0657",
        "volume":  "",
        "title_jp":  "日ソ関係（第8回ソ連に関する日米非公式協議）",
        "title_en":  "Japan-Soviet Relations: Eighth Informal Japan-US Consultations on the Soviet Union",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "GLOBAL;EAST_ASIA;EUROPE",
        "reaction_region_ids":  "",
        "entity_ids":  "JPN;USSR;USA",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_103489",
        "mofa_material_id":  "100-103489",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-103489",
        "legacy_archive_id":  "2014-4226",
        "legacy_record_id":  "legacy_2014_4226",
        "volume":  "",
        "title_jp":  "河本通商産業大臣サウディ・アラビア、エジプト、イラク訪問",
        "title_en":  "Visit by Minister of International Trade and Industry Komoto to Saudi Arabia, Egypt, and Iraq",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "",
        "primary_subject_en":  "",
        "region_ids":  "MIDEAST",
        "reaction_region_ids":  "",
        "entity_ids":  "JPN;SAU;EGY;IRQ",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "Auto-filled from MOFA Diplomatic Archives API exact bunruiNo search on 2026-06-25."
    },
    {
        "record_id":  "mofa_100_013445",
        "mofa_material_id":  "100-013445",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-013445",
        "legacy_archive_id":  "B\u0027.6.1.0.24-2",
        "legacy_record_id":  "legacy_b_6_1_0_24_2_vol2",
        "volume":  "2",
        "title_jp":  "アジア・アフリカ会議関係一件　諸外国の態度　第2巻",
        "title_en":  "Records Relating to the Asian-African Conference: Positions of Foreign Countries (Vol. 2)",
        "release_status":  "Partially Open",
        "years":  "",
        "primary_subject_jp":  "アジア・アフリカ会議：諸外国およびヴィエトミンの態度（第二巻）",
        "primary_subject_en":  "Asian-African Conference: Positions of Foreign Countries and the Viet Minh (Vol. 2)",
        "region_ids":  "AFRO_ASIA;ASIA;AFRICA",
        "reaction_region_ids":  "",
        "entity_ids":  "PRC;ROC",
        "organization_ids":  "VIET_MINH",
        "related_organization_ids":  "SEATO",
        "event_ids":  "BANDUNG_1955",
        "bloc_ids":  "",
        "keyword_ids":  "BANDUNG_CONFERENCE;FOREIGN_GOVERNMENT_ATTITUDES;GOVERNMENT_REACTIONS;PRC_ROC_COMPETITION;CONFERENCE_DIPLOMACY;NATIONAL_LIBERATION_MOVEMENT",
        "analytical_context_ids":  "",
        "entity_review_required":  "VIETNAM_ENTITY_AMBIGUOUS",
        "source_verified_note":  "User verified on current MOFA Diplomatic Archives web search system; material id added 2026-06-25."
    },
    {
        "record_id":  "mofa_100_023523",
        "mofa_material_id":  "100-023523",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-023523",
        "legacy_archive_id":  "B\u0027.6.1.0.34",
        "legacy_record_id":  "legacy_b_6_1_0_34_vol1",
        "volume":  "1",
        "title_jp":  "アジア・アフリカ人民連帯会議関係一件（アジア・アフリカ諸国民会議関係を含む）　第1巻",
        "title_en":  "Records Relating to the Afro-Asian People\u0027s Solidarity Conference, Including the Conference of Asian and African Peoples (Vol. 1)",
        "release_status":  "Access Review Required",
        "years":  "",
        "primary_subject_jp":  "アジア・アフリカ人民連帯会議／AAPSO系会議（第1巻）",
        "primary_subject_en":  "Afro-Asian People\u0027s Solidarity Conference / AAPSO Conference Series (Vol. 1)",
        "region_ids":  "ASIA;AFRICA;MIDEAST;AFRO_ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "JPN;PRC;USSR;IDN;IRQ;EGY;IRN",
        "organization_ids":  "AAPSO",
        "related_organization_ids":  "",
        "event_ids":  "AAPSO_CONFERENCE_SERIES",
        "bloc_ids":  "",
        "keyword_ids":  "AAPSO;AFRO_ASIAN_SOLIDARITY;PEOPLES_DIPLOMACY;THIRD_WORLD;ECON_COOP;PAN_AFRICAN;NATIONAL_LIBERATION_MOVEMENT",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "User verified on current MOFA Diplomatic Archives web search system; material id added 2026-06-25."
    },
    {
        "record_id":  "mofa_100_023524",
        "mofa_material_id":  "100-023524",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-023524",
        "legacy_archive_id":  "B\u0027.6.1.0.34",
        "legacy_record_id":  "legacy_b_6_1_0_34_vol2",
        "volume":  "2",
        "title_jp":  "アジア・アフリカ人民連帯会議関係一件（アジア・アフリカ諸国民会議関係を含む）　第2巻",
        "title_en":  "Records Relating to the Afro-Asian People\u0027s Solidarity Conference, Including the Conference of Asian and African Peoples (Vol. 2)",
        "release_status":  "Access Review Required",
        "years":  "",
        "primary_subject_jp":  "アジア・アフリカ人民連帯会議／AAPSO系会議（第2巻）",
        "primary_subject_en":  "Afro-Asian People\u0027s Solidarity Conference / AAPSO Conference Series (Vol. 2)",
        "region_ids":  "ASIA;AFRICA;MIDEAST;AFRO_ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "JPN;PRC;USSR;IDN;IRQ;EGY;IRN",
        "organization_ids":  "AAPSO",
        "related_organization_ids":  "",
        "event_ids":  "AAPSO_CONFERENCE_SERIES",
        "bloc_ids":  "",
        "keyword_ids":  "AAPSO;AFRO_ASIAN_SOLIDARITY;PEOPLES_DIPLOMACY;THIRD_WORLD;ECON_COOP;PAN_AFRICAN;NATIONAL_LIBERATION_MOVEMENT",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "User verified on current MOFA Diplomatic Archives web search system; material id added 2026-06-25."
    },
    {
        "record_id":  "mofa_100_023525",
        "mofa_material_id":  "100-023525",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-023525",
        "legacy_archive_id":  "B\u0027.6.1.0.34",
        "legacy_record_id":  "legacy_b_6_1_0_34_vol3",
        "volume":  "3",
        "title_jp":  "アジア・アフリカ人民連帯会議関係一件（アジア・アフリカ諸国民会議関係を含む）　第3巻",
        "title_en":  "Records Relating to the Afro-Asian People\u0027s Solidarity Conference, Including the Conference of Asian and African Peoples (Vol. 3)",
        "release_status":  "Access Review Required",
        "years":  "",
        "primary_subject_jp":  "アジア・アフリカ人民連帯会議／AAPSO系会議（第3巻）",
        "primary_subject_en":  "Afro-Asian People\u0027s Solidarity Conference / AAPSO Conference Series (Vol. 3)",
        "region_ids":  "ASIA;AFRICA;MIDEAST;AFRO_ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "JPN;PRC;USSR;IDN;IRQ;EGY;IRN",
        "organization_ids":  "AAPSO",
        "related_organization_ids":  "",
        "event_ids":  "AAPSO_CONFERENCE_SERIES",
        "bloc_ids":  "",
        "keyword_ids":  "AAPSO;AFRO_ASIAN_SOLIDARITY;PEOPLES_DIPLOMACY;THIRD_WORLD;ECON_COOP;PAN_AFRICAN;NATIONAL_LIBERATION_MOVEMENT",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "User verified on current MOFA Diplomatic Archives web search system; material id added 2026-06-25."
    },
    {
        "record_id":  "mofa_100_013468",
        "mofa_material_id":  "100-013468",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-013468",
        "legacy_archive_id":  "B\u0027.6.1.0.34",
        "legacy_record_id":  "legacy_b_6_1_0_34_vol4",
        "volume":  "4",
        "title_jp":  "アジア・アフリカ人民連帯会議関係一件（アジア・アフリカ諸国民会議関係を含む）　第4巻",
        "title_en":  "Records Relating to the Afro-Asian People\u0027s Solidarity Conference, Including the Conference of Asian and African Peoples (Vol. 4)",
        "release_status":  "Access Review Required",
        "years":  "",
        "primary_subject_jp":  "AAPSO系会議：組織構造・委員会・経済ゼミナール（第4巻）",
        "primary_subject_en":  "AAPSO Conference Series: Organizational Structure, Committees, and Economic Seminars (Vol. 4)",
        "region_ids":  "ASIA;AFRICA;MIDEAST;AFRO_ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "JPN;PRC;USSR;IDN;IRQ;EGY;IRN",
        "organization_ids":  "AAPSO",
        "related_organization_ids":  "",
        "event_ids":  "AAPSO_CONFERENCE_SERIES",
        "bloc_ids":  "",
        "keyword_ids":  "AAPSO;AFRO_ASIAN_SOLIDARITY;PEOPLES_DIPLOMACY;THIRD_WORLD;ECON_COOP;PAN_AFRICAN;NATIONAL_LIBERATION_MOVEMENT;ORGANIZATIONAL_STRUCTURE;COMMITTEE_ACTIVITIES;ECONOMIC_SEMINAR;TRANSNATIONAL_POLITICAL_ORGANIZATION",
        "analytical_context_ids":  "",
        "entity_review_required":  "",
        "source_verified_note":  "User verified on current MOFA Diplomatic Archives web search system; material id added 2026-06-25."
    },
    {
        "record_id":  "mofa_100_030772",
        "mofa_material_id":  "100-030772",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-030772",
        "legacy_archive_id":  "A\u0027.4.1.1.3-1",
        "legacy_record_id":  "legacy_a_4_1_1_3_1_vol3",
        "volume":  "3",
        "title_jp":  "中華人民共和国内政並びに国情関係雑件　独立関係（承認問題を含む）　第3巻",
        "title_en":  "Miscellaneous Records on Domestic Affairs and Conditions in the People\u0027s Republic of China: Independence and Recognition Issues (Vol. 3)",
        "release_status":  "Open",
        "years":  "1958-1966",
        "primary_subject_jp":  "中華人民共和国：独立関係および政権承認問題",
        "primary_subject_en":  "PRC: Independence and Recognition Issues",
        "region_ids":  "GLOBAL;EAST_ASIA",
        "reaction_region_ids":  "AFRICA;LATIN_AMERICA;EUROPE;MIDEAST;SOUTHEAST_ASIA",
        "entity_ids":  "PRC;ROC;SEN;GHA;CUB;NYASALAND;PRT;ARG;COG;FRG;MYS;BRA;POL;IRQ;MDG;TUR;YEM;ETH;SLE;NGA;DNK;ZMB;SDN;BEN;IDN;MWI;TUN;KWT;LAO",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "DIPLOMATIC_RECOGNITION;GOVERNMENT_RECOGNITION_ISSUE;RECOGNITION_COMPETITION;PRC_ROC_COMPETITION;FOREIGN_GOVERNMENT_ATTITUDES;JAPANESE_DIPLOMATIC_REPORTING",
        "analytical_context_ids":  "DECOLONIZATION_AND_UN_DIPLOMACY;POSTCOLONIAL_STATES_AND_CHINA_REPRESENTATION",
        "entity_review_required":  "NYASALAND_HISTORICAL_TERRITORY;WEST_GERMANY_HISTORICAL_STATE;YEMEN_ENTITY_AMBIGUOUS",
        "source_verified_note":  "Added from user-provided MOFA material detail and checked against MOFA API on 2026-06-25. MOFA API returned material_id 100-030772, classification A\u0027.4.1.1.3-1, date range 1958-06-01 to 1966-09-30, and publication date 1997-02-24."
    },
    {
        "record_id":  "mofa_100_030171",
        "mofa_material_id":  "100-030171",
        "source_url":  "https://da.mofa.go.jp/material-detail?id=100-030171",
        "legacy_archive_id":  "A\u0027.2.2.0.BM/C(C)1",
        "legacy_record_id":  "legacy_a_2_2_0_bm_c_c_1",
        "volume":  "",
        "title_jp":  "ビルマ・中共間外交関係雑集",
        "title_en":  "Miscellaneous Records on Burma-PRC Diplomatic Relations",
        "release_status":  "Open",
        "years":  "1954-1972",
        "primary_subject_jp":  "ビルマ・中共間外交関係および中共の対ビルマ政治工作",
        "primary_subject_en":  "Burma-PRC Diplomatic Relations and PRC Political Work in Burma",
        "region_ids":  "EAST_ASIA;SOUTHEAST_ASIA",
        "reaction_region_ids":  "",
        "entity_ids":  "MMR;PRC;ROC;JPN",
        "organization_ids":  "",
        "related_organization_ids":  "",
        "event_ids":  "",
        "bloc_ids":  "",
        "keyword_ids":  "BILAT;PRC_BURMA_RELATIONS;POLITICAL_WORK;INFLUENCE_OPERATIONS;DIPLOMATIC_RECOGNITION;JAPANESE_DIPLOMATIC_REPORTING",
        "analytical_context_ids":  "COLD_WAR_IN_SOUTHEAST_ASIA;REGIONAL_SECURITY_IN_SOUTHEAST_ASIA;SOUTHEAST_ASIAN_COMMUNIST_POLITICS",
        "entity_review_required":  "",
        "source_verified_note":  "Added from user-provided MOFA and JACAR metadata and checked against MOFA API on 2026-06-25. MOFA API returned material_id 100-030171, classification A\u0027.2.2.0.BM/C(C)1, date range 1954-11-01 to 1972-05-31, publication date 1997-02-24, and JACAR reference code B20010089700. JACAR metadata supplied by user: scale 52, date range Showa 29-11-16 to Showa 47-05, creators include Consul General Konagaya at Rangoon, Japanese Embassy in Burma, Japanese Embassy in the Republic of China, and Japanese overseas missions. User noted content concerning PRC political work toward Myanmar/Burma."
    }
];
